adds missing .dockerignore files and other security related patches

diff --git a/.github/workflows/gas_system.yml b/.github/workflows/gas_system.yml
--- a/.github/workflows/gas_system.yml
+++ b/.github/workflows/gas_system.yml
@@ -52,6 +52,25 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Validate .gitignore and .dockerignore
+        run: |
+          if [ ! -f .gitignore ]; then
+            echo "Error: .gitignore file not found.";
+            exit 1;
+          fi
+          if [ ! -f gas_system/.dockerignore ]; then
+            echo "Error: .dockerignore file not found in gas_system directory.";
+            exit 1;
+          fi
+          if ! grep -q '^[[:space:]]*\.env' .gitignore; then
+            echo "Error: .env is either not in .gitignore or it's commented out.";
+            exit 1;
+          fi
+          if ! grep -q '^[[:space:]]*\.env' gas_system/.dockerignore; then
+            echo "Error: .env is either not in .dockerignore in gas_system directory or it's commented out.";
+            exit 1;
+          fi
+
       - name: Set up python
         id: setup-python
         uses: actions/setup-python@v2
diff --git a/wormhole/spy_listener/Makefile b/wormhole/spy_listener/Makefile
--- a/wormhole/spy_listener/Makefile
+++ b/wormhole/spy_listener/Makefile
@@ -29,13 +29,23 @@ lint:
 run:
 	python -m app --reload
 
-make run-container:
+check-dockerignore:
+	@if [ ! -f .dockerignore ]; then \
+		echo "Error: .dockerignore file not found. Please add a .dockerignore file before proceeding."; \
+		exit 1; \
+	fi
+	@if ! grep -q '^[[:space:]]*\.env' .dockerignore; then \
+		echo "Error: .env was not found in .dockerignore. Please add it before proceeding."; \
+		exit 1; \
+	fi
+
+run-container: check-dockerignore
 	docker-compose up -d
 
-build:
+build: check-dockerignore
 	docker build -t $(docker_username)/$(docker_image):latest .
 
-push:
+push: check-dockerignore
 	docker push $(docker_username)/$(docker_image):latest
 
 test:
